/**
 * Describes how the output target is embedded into the generated runtime.
 *
 * - "file": a fixed output file path is embedded as a literal. ktzm.outputFilePath
 *   is readable and writable but changes are not reflected in the actual output path.
 * - "directory": the runtime writes output content and the final ktzm.outputFilePath
 *   value to temporary files. The renderer reads them after Worker exit and performs
 *   validation + final file placement.
 */
export type OutputEmbed =
  | { kind: "file"; filePath: string; initialRelativePath: string }
  | { kind: "directory"; contentTmpPath: string; pathTmpPath: string; initialRelativePath: string };

/**
 * Generates the source code of the Katazome runtime file (ktzm-runtime.ts).
 *
 * Three modes depending on outputEmbed:
 *   - omitted: stdout mode (used by `ktzm transpile`). Output goes to stdout.
 *     KTZM_OUTPUT_FILE_PATH sets the initial value of ktzm.outputFilePath.
 *   - { kind: "file" }: file mode. Output goes to a fixed absolute path.
 *     ktzm.outputFilePath is readable/writable but does not affect the output path.
 *   - { kind: "directory" }: directory mode. Output content and the final
 *     ktzm.outputFilePath value are written to temporary files for the renderer.
 *
 * @param inputData   Parsed input data to embed as a JSON literal.
 * @param answerData  Resolved question answers to embed as a JSON literal.
 * @param outputEmbed Describes how output is directed (see OutputEmbed).
 */
export function generateRuntimeContent(
  inputData: unknown,
  answerData: unknown,
  outputEmbed?: OutputEmbed,
): string {
  const inputJson = JSON.stringify(inputData ?? {});
  const answerJson = JSON.stringify(answerData ?? {});

  if (outputEmbed === undefined) {
    return generateStdoutModeRuntime(inputJson, answerJson);
  } else if (outputEmbed.kind === "file") {
    return generateFileModeRuntime(inputJson, answerJson, outputEmbed.filePath, outputEmbed.initialRelativePath);
  } else {
    return generateDirectoryModeRuntime(inputJson, answerJson, outputEmbed.contentTmpPath, outputEmbed.pathTmpPath, outputEmbed.initialRelativePath);
  }
}

function generateStdoutModeRuntime(inputJson: string, answerJson: string): string {
  return `\
// ktzm-runtime.ts
// Runtime library for Katazome transpiled templates.
// Do not edit manually — this file is generated by \`ktzm transpile\`.
import { writeFileSync } from "node:fs";

const inputData: unknown = ${inputJson};

const answerData: unknown = ${answerJson};

const chunks: string[] = [];

let _outputRelativePath: string = process.env["KTZM_OUTPUT_FILE_PATH"] ?? "";

const ktzm = {
  out(s: string): void {
    chunks.push(s);
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  get input(): any {
    return inputData as any;
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  get answer(): any {
    return answerData as any;
  },
  get outputFilePath(): string {
    return _outputRelativePath;
  },
  set outputFilePath(value: string) {
    _outputRelativePath = value;
  },
};

let outputWritten = false;
function writeOutput(): void {
  if (outputWritten) return;
  outputWritten = true;
  const content = chunks.join("");
  process.stdout.write(content);
}
process.on("beforeExit", writeOutput);
process.on("exit", writeOutput);

export default ktzm;
`;
}

function generateFileModeRuntime(
  inputJson: string,
  answerJson: string,
  filePath: string,
  initialRelativePath: string,
): string {
  return `\
// ktzm-runtime.ts
// Runtime library for Katazome transpiled templates.
// Do not edit manually — this file is generated by \`ktzm transpile\`.
import { writeFileSync } from "node:fs";

const _outputFileAbs: string = ${JSON.stringify(filePath)};

const inputData: unknown = ${inputJson};

const answerData: unknown = ${answerJson};

const chunks: string[] = [];

let _outputRelativePath: string = ${JSON.stringify(initialRelativePath)};

const ktzm = {
  out(s: string): void {
    chunks.push(s);
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  get input(): any {
    return inputData as any;
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  get answer(): any {
    return answerData as any;
  },
  get outputFilePath(): string {
    return _outputRelativePath;
  },
  set outputFilePath(value: string) {
    _outputRelativePath = value;
  },
};

let outputWritten = false;
function writeOutput(): void {
  if (outputWritten) return;
  outputWritten = true;
  const content = chunks.join("");
  writeFileSync(_outputFileAbs, content);
}
process.on("beforeExit", writeOutput);
process.on("exit", writeOutput);

export default ktzm;
`;
}

function generateDirectoryModeRuntime(
  inputJson: string,
  answerJson: string,
  contentTmpPath: string,
  pathTmpPath: string,
  initialRelativePath: string,
): string {
  return `\
// ktzm-runtime.ts
// Runtime library for Katazome transpiled templates.
// Do not edit manually — this file is generated by \`ktzm transpile\`.
import { writeFileSync } from "node:fs";

const _contentTmpPath: string = ${JSON.stringify(contentTmpPath)};
const _pathTmpPath: string = ${JSON.stringify(pathTmpPath)};

const inputData: unknown = ${inputJson};

const answerData: unknown = ${answerJson};

const chunks: string[] = [];

let _outputRelativePath: string = ${JSON.stringify(initialRelativePath)};

const ktzm = {
  out(s: string): void {
    chunks.push(s);
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  get input(): any {
    return inputData as any;
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  get answer(): any {
    return answerData as any;
  },
  get outputFilePath(): string {
    return _outputRelativePath;
  },
  set outputFilePath(value: string) {
    _outputRelativePath = value;
  },
};

let outputWritten = false;
function writeOutput(): void {
  if (outputWritten) return;
  outputWritten = true;
  const content = chunks.join("");
  writeFileSync(_contentTmpPath, content);
  writeFileSync(_pathTmpPath, _outputRelativePath);
}
process.on("beforeExit", writeOutput);
process.on("exit", writeOutput);

export default ktzm;
`;
}
