/**
 * Generates the source code of the Katazome runtime file (ktzm-runtime.ts)
 * with the given input data embedded as a JSON literal.
 *
 * The generated file is written to disk when `ktzm transpile` is run so that
 * the user can execute it directly with `bun run <transpiled-file>`.
 * It is also written to a temporary location when `ktzm generate` is run.
 *
 * The runtime:
 *   - Has input data embedded as a JSON literal (no external file needed).
 *   - Exposes a `ktzm` default export with `out()` and `input`.
 *   - On process exit, writes all accumulated output to KTZM_OUTPUT_FILE,
 *     or to stdout if the env var is not set.
 */
export function generateRuntimeContent(inputData: unknown): string {
  const inputJson = JSON.stringify(inputData ?? {});
  return `\
// ktzm-runtime.ts
// Runtime library for Katazome transpiled templates.
// Do not edit manually — this file is generated by \`ktzm transpile\`.
import { writeFileSync } from "node:fs";

const outputFilePath = process.env["KTZM_OUTPUT_FILE"];

const inputData: unknown = ${inputJson};

const chunks: string[] = [];

const ktzm = {
  out(s: string): void {
    chunks.push(s);
  },
  // Input data is typed as any so that templates can access properties
  // freely (e.g. ktzm.input.foobar) without TypeScript errors.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  get input(): any {
    return inputData as any;
  },
};

let outputWritten = false;
function writeOutput(): void {
  if (outputWritten) return;
  outputWritten = true;
  const content = chunks.join("");
  if (outputFilePath) {
    writeFileSync(outputFilePath, content);
  } else {
    process.stdout.write(content);
  }
}
process.on("beforeExit", writeOutput);
process.on("exit", writeOutput);

export default ktzm;
`;
}
